name: Feature Request
description: Suggest a new feature or enhancement for Canvas LMS Kit
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible.
        
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Canvas API implementation
        - Enhancement to existing API
        - New helper method/functionality
        - Performance improvement
        - Developer experience improvement
        - Documentation improvement
        - Other
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem you're trying to solve
      placeholder: "I need to be able to..."
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: "Add a method that..."
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I've tried using..."
      
  - type: textarea
    id: code-example
    attributes:
      label: Example Usage
      description: Show how the feature would be used
      render: php
      placeholder: |
        <?php
        use CanvasLMS\Api\Courses\Course;
        
        // Example of how the feature would work
        $course = Course::find(123);
        $result = $course->newFeatureMethod();
        
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      
  - type: checkboxes
    id: willing-to-help
    attributes:
      label: Contribution
      options:
        - label: I am willing to help implement this feature
          required: false