name: Deploy Doc to GitHub Pages

on:
    push:
      branches: [ "main" ]

jobs:
    # Build job
    build:
        runs-on: ubuntu-latest

        steps:
          # Checkout the repository
          - name: Checkout Repository
            uses: actions/checkout@v2

          # Generate Documentation
          - name: Generate Documentation
            run: docker run --rm --volume "$(pwd):/data" phpdoc/phpdoc:3
    
          # Upload documentation as an artifact
          - name: Upload Documentation Artifact
            uses: actions/upload-artifact@v2
            with:
              name: Documentation
              path: ./docs/api
  
    # Deploy job
    deploy:
      # Add a dependency to the build job
      needs: build
  
      # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
      permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source
  
      # Deploy to the github-pages environment
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
  
      # Specify runner + deployment step
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4