name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, curl, json
          coverage: xdebug
          tools: composer:v2
          
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
        
      - name: Run all quality checks
        run: composer check
        
      - name: Generate coverage report
        run: vendor/bin/phpunit tests --coverage-clover=coverage/clover.xml
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/clover.xml

  notify-packagist:
    name: Update Packagist
    needs: quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify Packagist
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_API_TOKEN: ${{ secrets.PACKAGIST_API_TOKEN }}
        run: |
          if [[ -n "$PACKAGIST_USERNAME" && -n "$PACKAGIST_API_TOKEN" ]]; then
            echo "Updating Packagist..."
            curl -XPOST -H'content-type:application/json' \
              "https://packagist.org/api/update-package?username=$PACKAGIST_USERNAME&apiToken=$PACKAGIST_API_TOKEN" \
              -d'{"repository":{"url":"https://github.com/jjuanrivvera/canvas-lms-kit"}}'
          else
            echo "::warning::Packagist webhook not configured. Please update Packagist manually."
            echo "::warning::Add PACKAGIST_USERNAME and PACKAGIST_API_TOKEN secrets in repository settings."
          fi